### PR TITLE
Fix Windows Unicode Bug

### PR DESCRIPTION
**Pull request by 0xsuid**
Resolved below error by opening file with utf-8 encoding.

Windows: Error e 'charmap' codec can't encode character '\u2264' in position 258

### CODE REVIEW

**Comment by idimou** [comment]
Tested: Works when creating CSVs. Needs one more modification to fix UTF issue when reading CSVs to populate DB.

**Review by idimou — CHANGES_REQUESTED** [review]
add `encoding='utf8'` in line 310 as well

**Comment by 0xsuid** [comment]
Updated @idimou @aatlasis

**Review by aatlasis — APPROVED** [review]
Many thanks!

**Comment by aatlasis** [comment]
Many thanks for your contribution

**Pull request closed without merging**
